site_name: DVS Study
pages:
- Inicio: 'index.md'
- Proyecto:
    - 'Estructura': 'project/structure.md'
    - 'Pruebas': 'project/base.md'
    - 'Calibración': 'project/calibration.md'
    - 'Como contribuir': 'project/contribute.md'   
- Referencias: 'references.md'

theme: readthedocs
